---

#- name: Обновить все пакеты до последней версии
#  ansible.builtin.apt:
#    update_cache: yes
#  become: true

- name: Проверка, установлен ли каждый пакет
  command: dpkg -s {{ item }}
  register: package_status
  failed_when: "package_status.rc != 0 and 'not installed' not in package_status.stderr"
  with_items: "{{ jupyter_apt_packages }}"
  changed_when: false

- name: Установите пакеты apt, если они еще не установлены
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ jupyter_apt_packages }}"
  when: package_status.results | selectattr('rc', 'equalto', 1) | map(attribute='item') | list | length > 0
  become: true


- name: Проверка директории JPH
  stat: 
    path: /opt/tljh
  register: jupyterhub_directory
  changed_when: false
  become: true

- name: "Start installation process"
  shell: "curl -L https://tljh.jupyter.org/bootstrap.py | sudo -E python3 - --admin {{ jupyter_admin_user }}"
  when: not jupyterhub_directory.stat.exists
  become: true

- name: Проверка стартовой страницы
  uri:
    url: "http://{{ ansible_play_hosts | join('') }}"
    method: GET
  register: app_status
  until: app_status.status == 200 or ansible_check_mode
  retries: 10
  delay: 6
  when: not ansible_check_mode
  become: true

- name: Показать адресс JPH
  debug:
    msg:
      - "Start page available in: http://{{ ansible_play_hosts | join('') }}"
      - "Admin user name: {{ jupyter_admin_user }}"

- name: Проверка nbgitpuller уже установлен или нет
  command: pip show nbgitpuller
  register: nbgitpuller_status
  ignore_errors: true
  changed_when: false
  become: true

- name: Установка nbgitpuller
  pip:
    name: nbgitpuller
    state: present
  when: nbgitpuller_status.rc != 0 and not ansible_check_mode
  become: true

- name: Выполнить команду mamba -V
  command: /opt/tljh/user/bin/mamba -V
  become: true
  when: not ansible_check_mode


- name: Выполнить команду mamba install -y -c conda-forge xeus-cling
  command: /opt/tljh/user/bin/mamba install -y -c conda-forge xeus-cling
  become: true
  when: not ansible_check_mode

- name: Выполнить команду mamba create  -y --name everest python=2.7
  command: /opt/tljh/user/bin/mamba create  -y --name everest python=2.7
  become: true
  when: not ansible_check_mode











